# Generated by Django 5.2.6 on 2025-09-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
