# Generated by Django 5.2.6 on 2025-09-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'branch')},
        ),
    ]
