# Generated by Django 5.2.6 on 2025-09-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0004_item_supplier_alter_category_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
