# Generated by Django 5.2.6 on 2025-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='new_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
