# Generated by Django 5.2.6 on 2025-09-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_activitylog_new_data_activitylog_old_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
