# Generated by Django 5.2.6 on 2025-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_sale_card_amount_sale_cash_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='card_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
