# Generated by Django 5.2.6 on 2025-09-21 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_email'),
        ('sales', '0006_alter_sale_card_amount_alter_sale_cash_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='sale',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
    ]
