# Generated by Django 5.2.6 on 2025-09-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_customer_remove_saledetail_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
