# Generated by Django 5.2.6 on 2025-10-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='takeaway', max_length=20),
        ),
    ]
